#pragma once

#include "../../Config.h"

#define CPPHTTPLIB_THREAD_POOL_COUNT Config::SERVER_NUM_THREADS
#define CPPHTTPLIB_KEEPALIVE_MAX_COUNT Config::SERVER_KEEPALIVE_MAX_COUNT
#define CPPHTTPLIB_CONNECTION_TIMEOUT_SECOND 2
#define CPPHTTPLIB_SERVER_READ_TIMEOUT_SECOND Config::SERVER_READ_TIMEOUT
#define CPPHTTPLIB_SERVER_WRITE_TIMEOUT_SECOND Config::SERVER_WRITE_TIMEOUT
#define CPPHTTPLIB_RECV_FLAGS 0
#define CPPHTTPLIB_IDLE_INTERVAL_SECOND 0
#define CPPHTTPLIB_IDLE_INTERVAL_USECOND 0
