#ifndef COUNTRYDATA_H
#define COUNTRYDATA_H

#include <string>
#include <map>
#include <vector>

std::map<std::string, std::string> countryCodes = {
    {"AF", "Afghanistan"},
    {"AL", "Albania"},
    {"DZ", "Algeria"},
    {"AD", "Andorra"},
    {"AO", "Angola"},
    {"AG", "Antigua and Barbuda"},
    {"AR", "Argentina"},
    {"AM", "Armenia"},
    {"AU", "Australia"},
    {"AT", "Austria"},
    {"AZ", "Azerbaijan"},
    {"BS", "Bahamas"},
    {"BH", "Bahrain"},
    {"BD", "Bangladesh"},
    {"BB", "Barbados"},
    {"BY", "Belarus"},
    {"BE", "Belgium"},
    {"BZ", "Belize"},
    {"BJ", "Benin"},
    {"BT", "Bhutan"},
    {"BO", "Bolivia"},
    {"BA", "Bosnia and Herzegovina"},
    {"BW", "Botswana"},
    {"BR", "Brazil"},
    {"BN", "Brunei"},
    {"BG", "Bulgaria"},
    {"BF", "Burkina Faso"},
    {"BI", "Burundi"},
    {"KH", "Cambodia"},
    {"CM", "Cameroon"},
    {"CA", "Canada"},
    {"CV", "Cape Verde"},
    {"CF", "Central African Republic"},
    {"TD", "Chad"},
    {"CL", "Chile"},
    {"CN", "China"},
    {"CO", "Colombia"},
    {"KM", "Comoros"},
    {"CG", "Congo (Brazzaville)"},
    {"CD", "Congo (Kinshasa)"},
    {"CR", "Costa Rica"},
    {"CI", "Côte d'Ivoire"},
    {"HR", "Croatia"},
    {"CU", "Cuba"},
    {"CY", "Cyprus"},
    {"CZ", "Czechia"},
    {"DK", "Denmark"},
    {"DJ", "Djibouti"},
    {"DM", "Dominica"},
    {"DO", "Dominican Republic"},
    {"EC", "Ecuador"},
    {"EG", "Egypt"},
    {"SV", "El Salvador"},
    {"GQ", "Equatorial Guinea"},
    {"ER", "Eritrea"},
    {"EE", "Estonia"},
    {"SZ", "Eswatini"},
    {"ET", "Ethiopia"},
    {"FJ", "Fiji"},
    {"FI", "Finland"},
    {"FR", "France"},
    {"GA", "Gabon"},
    {"GM", "Gambia"},
    {"GE", "Georgia"},
    {"DE", "Germany"},
    {"GH", "Ghana"},
    {"GR", "Greece"},
    {"GD", "Grenada"},
    {"GT", "Guatemala"},
    {"GN", "Guinea"},
    {"GW", "Guinea-Bissau"},
    {"GY", "Guyana"},
    {"HT", "Haiti"},
    {"HN", "Honduras"},
    {"HU", "Hungary"},
    {"IS", "Iceland"},
    {"IN", "India"},
    {"ID", "Indonesia"},
    {"IR", "Iran"},
    {"IQ", "Iraq"},
    {"IE", "Ireland"},
    {"IL", "Israel"},
    {"IT", "Italy"},
    {"JM", "Jamaica"},
    {"JP", "Japan"},
    {"JO", "Jordan"},
    {"KZ", "Kazakhstan"},
    {"KE", "Kenya"},
    {"KI", "Kiribati"},
    {"KR", "Korea (South)"},
    {"KW", "Kuwait"},
    {"KG", "Kyrgyzstan"},
    {"LA", "Laos"},
    {"LV", "Latvia"},
    {"LB", "Lebanon"},
    {"LS", "Lesotho"},
    {"LR", "Liberia"},
    {"LY", "Libya"},
    {"LI", "Liechtenstein"},
    {"LT", "Lithuania"},
    {"LU", "Luxembourg"},
    {"MG", "Madagascar"},
    {"MW", "Malawi"},
    {"MY", "Malaysia"},
    {"MV", "Maldives"},
    {"ML", "Mali"},
    {"MT", "Malta"},
    {"MH", "Marshall Islands"},
    {"MR", "Mauritania"},
    {"MU", "Mauritius"},
    {"MX", "Mexico"},
    {"FM", "Micronesia"},
    {"MD", "Moldova"},
    {"MC", "Monaco"},
    {"MN", "Mongolia"},
    {"ME", "Montenegro"},
    {"MA", "Morocco"},
    {"MZ", "Mozambique"},
    {"MM", "Myanmar"},
    {"NA", "Namibia"},
    {"NR", "Nauru"},
    {"NP", "Nepal"},
    {"NL", "Netherlands"},
    {"NZ", "New Zealand"},
    {"NI", "Nicaragua"},
    {"NE", "Niger"},
    {"NG", "Nigeria"},
    {"NO", "Norway"},
    {"OM", "Oman"},
    {"PK", "Pakistan"},
    {"PW", "Palau"},
    {"PS", "Palestine"},
    {"PA", "Panama"},
    {"PG", "Papua New Guinea"},
    {"PY", "Paraguay"},
    {"PE", "Peru"},
    {"PH", "Philippines"},
    {"PL", "Poland"},
    {"PT", "Portugal"},
    {"QA", "Qatar"},
    {"RO", "Romania"},
    {"RU", "Russia"},
    {"RW", "Rwanda"},
    {"KN", "Saint Kitts and Nevis"},
    {"LC", "Saint Lucia"},
    {"VC", "Saint Vincent and the Grenadines"},
    {"WS", "Samoa"},
    {"SM", "San Marino"},
    {"ST", "São Tomé and Príncipe"},
    {"SA", "Saudi Arabia"},
    {"SN", "Senegal"},
    {"RS", "Serbia"},
    {"SC", "Seychelles"},
    {"SL", "Sierra Leone"},
    {"SG", "Singapore"},
    {"SK", "Slovakia"},
    {"SI", "Slovenia"},
    {"SB", "Solomon Islands"},
    {"SO", "Somalia"},
    {"ZA", "South Africa"},
    {"ES", "Spain"},
    {"LK", "Sri Lanka"},
    {"SD", "Sudan"},
    {"SR", "Suriname"},
    {"SE", "Sweden"},
    {"CH", "Switzerland"},
    {"SY", "Syria"},
    {"TW", "Taiwan"},
    {"TJ", "Tajikistan"},
    {"TZ", "Tanzania"},
    {"TH", "Thailand"},
    {"TL", "Timor-Leste"},
    {"TG", "Togo"},
    {"TO", "Tonga"},
    {"TT", "Trinidad and Tobago"},
    {"TN", "Tunisia"},
    {"TR", "Turkey"},
    {"TM", "Turkmenistan"},
    {"TV", "Tuvalu"},
    {"UG", "Uganda"},
    {"UA", "Ukraine"},
    {"AE", "United Arab Emirates"},
    {"GB", "United Kingdom"},
    {"US", "United States"},
    {"UY", "Uruguay"},
    {"UZ", "Uzbekistan"},
    {"VU", "Vanuatu"},
    {"VE", "Venezuela"},
    {"VN", "Vietnam"},
    {"YE", "Yemen"},
    {"ZM", "Zambia"},
    {"ZW", "Zimbabwe"}};
 
std::map<std::string, std::vector<std::string>> countryNeighbours = {
    {"AF", {"Iran", "Pakistan", "Turkmenistan", "Uzbekistan", "Tajikistan", "China"}},
    {"AL", {"Montenegro", "Kosovo", "North Macedonia", "Greece"}},
    {"DZ", {"Tunisia", "Libya", "Niger", "Mali", "Mauritania", "Western Sahara", "Morocco"}},
    {"AD", {"France", "Spain"}},
    {"AO", {"Namibia", "Zambia", "Democratic Republic of the Congo"}},
    {"AG", {}},
    {"AR", {"Chile", "Bolivia", "Paraguay", "Brazil", "Uruguay"}},
    {"AM", {"Georgia", "Turkey", "Iran", "Azerbaijan"}},
    {"AU", {}},
    {"AT", {"Germany", "Czechia", "Slovakia", "Hungary", "Slovenia", "Italy", "Switzerland", "Liechtenstein"}},
    {"AZ", {"Russia", "Georgia", "Armenia", "Iran"}},
    {"BS", {}},
    {"BD", {"India", "Myanmar"}},
    {"BB", {}},
    {"BY", {"Russia", "Ukraine", "Poland", "Lithuania", "Latvia"}},
    {"BE", {"Netherlands", "Germany", "Luxembourg", "France"}},
    {"BZ", {"Mexico", "Guatemala"}},
    {"BJ", {"Burkina Faso", "Niger", "Nigeria", "Togo"}},
    {"BT", {"India", "China"}},
    {"BO", {"Brazil", "Paraguay", "Argentina", "Chile", "Peru"}},
    {"BA", {"Croatia", "Montenegro", "Serbia"}},
    {"BW", {"Namibia", "Zimbabwe", "South Africa", "Zambia"}},
    {"BR", {"Argentina", "Bolivia", "Colombia", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela"}},
    {"BN", {"Malaysia"}},
    {"BG", {"Romania", "Serbia", "North Macedonia", "Greece", "Turkey"}},
    {"BF", {"Mali", "Niger", "Benin", "Togo", "Ghana", "Ivory Coast"}},
    {"BI", {"Rwanda", "Tanzania", "Democratic Republic of the Congo"}},
    {"KH", {"Thailand", "Vietnam", "Laos"}},
    {"CM", {"Nigeria", "Chad", "Central African Republic", "Equatorial Guinea", "Gabon", "Republic of the Congo"}},
    {"CA", {"United States"}},
    {"CV", {}},
    {"CF", {"Chad", "Sudan", "South Sudan", "Democratic Republic of the Congo", "Republic of the Congo", "Cameroon"}},
    {"TD", {"Libya", "Sudan", "Central African Republic", "Cameroon", "Nigeria", "Niger"}},
    {"CL", {"Peru", "Bolivia", "Argentina"}},
    {"CN", {"Russia", "Mongolia", "North Korea", "Vietnam", "Laos", "Myanmar", "India", "Bhutan", "Nepal", "Pakistan", "Afghanistan", "Tajikistan", "Kyrgyzstan", "Kazakhstan"}},
    {"CO", {"Panama", "Venezuela", "Brazil", "Peru", "Ecuador"}},
    {"KM", {}},
    {"CG", {"Gabon", "Cameroon", "Central African Republic", "Democratic Republic of the Congo", "Angola"}},
    {"CD", {"Republic of the Congo", "Central African Republic", "South Sudan", "Uganda", "Rwanda", "Burundi", "Tanzania", "Zambia", "Angola"}},
    {"CR", {"Nicaragua", "Panama"}},
    {"CI", {"Liberia", "Guinea", "Mali", "Burkina Faso", "Ghana"}},
    {"HR", {"Slovenia", "Hungary", "Serbia", "Bosnia and Herzegovina", "Montenegro"}},
    {"CU", {}},
    {"CY", {}},
    {"CZ", {"Germany", "Poland", "Slovakia", "Austria"}},
    {"DK", {"Germany"}},
    {"DJ", {"Eritrea", "Ethiopia", "Somalia"}},
    {"DM", {}},
    {"DO", {"Haiti"}},
    {"EC", {"Colombia", "Peru"}},
    {"EG", {"Libya", "Sudan", "Israel"}},
    {"SV", {"Guatemala", "Honduras"}},
    {"GQ", {"Cameroon", "Gabon"}},
    {"ER", {"Sudan", "Ethiopia", "Djibouti"}},
    {"EE", {"Latvia", "Russia"}},
    {"SZ", {"South Africa", "Mozambique"}},
    {"ET", {"Eritrea", "Djibouti", "Somalia", "Kenya", "South Sudan", "Sudan"}},
    {"FJ", {}},
    {"FI", {"Sweden", "Norway", "Russia"}},
    {"FR", {"Belgium", "Luxembourg", "Germany", "Switzerland", "Italy", "Spain", "Andorra", "Monaco"}},
    {"GA", {"Equatorial Guinea", "Cameroon", "Republic of the Congo"}},
    {"GM", {"Senegal"}},
    {"GE", {"Russia", "Turkey", "Armenia", "Azerbaijan"}},
    {"DE", {"Netherlands", "Belgium", "Luxembourg", "France", "Switzerland", "Austria", "Czechia", "Poland", "Denmark"}},
    {"GH", {"Ivory Coast", "Burkina Faso", "Togo"}},
    {"GR", {"Albania", "North Macedonia", "Bulgaria", "Turkey"}},
    {"GD", {}},
    {"GT", {"Mexico", "Belize", "Honduras", "El Salvador"}},
    {"GN", {"Guinea-Bissau", "Senegal", "Mali", "Sierra Leone", "Liberia", "Ivory Coast"}},
    {"GW", {"Senegal", "Guinea"}},
    {"GY", {"Venezuela", "Brazil", "Suriname"}},
    {"HT", {"Dominican Republic"}},
    {"HN", {"Guatemala", "El Salvador", "Nicaragua"}},
    {"HU", {"Slovakia", "Ukraine", "Romania", "Serbia", "Croatia", "Slovenia", "Austria"}},
    {"IS", {}},
    {"IN", {"Pakistan", "China", "Nepal", "Bhutan", "Bangladesh", "Myanmar"}},
    {"ID", {"Papua New Guinea", "East Timor", "Malaysia"}},
    {"IR", {"Armenia", "Azerbaijan", "Turkmenistan", "Afghanistan", "Pakistan", "Turkey", "Iraq"}},
    {"IQ", {"Turkey", "Syria", "Jordan", "Saudi Arabia", "Kuwait", "Iran"}},
    {"IE", {"United Kingdom"}},
    {"IL", {"Egypt", "Jordan", "Syria", "Lebanon"}},
    {"IT", {"France", "Switzerland", "Austria", "Slovenia"}},
    {"JM", {}},
    {"JP", {}},
    {"JO", {"Syria", "Iraq", "Saudi Arabia", "Israel"}},
    {"KZ", {"Russia", "China", "Kyrgyzstan", "Uzbekistan", "Turkmenistan"}},
    {"KE", {"Uganda", "Sudan", "Ethiopia", "Somalia", "Tanzania"}},
    {"KI", {}},
    {"KR", {"North Korea"}},
    {"KW", {"Iraq", "Saudi Arabia"}},
    {"KG", {"Kazakhstan", "Uzbekistan", "Tajikistan", "China"}},
    {"LA", {"China", "Vietnam", "Cambodia", "Thailand", "Myanmar"}},
    {"LV", {"Estonia", "Lithuania", "Russia", "Belarus"}},
    {"LB", {"Syria", "Israel"}},
    {"LS", {"South Africa"}},
    {"LR", {"Guinea", "Ivory Coast", "Sierra Leone"}},
    {"LY", {"Tunisia", "Algeria", "Niger", "Chad", "Sudan", "Egypt"}},
    {"LI", {"Switzerland", "Austria"}},
    {"LT", {"Latvia", "Belarus", "Poland"}},
    {"LU", {"Belgium", "Germany", "France"}},
    {"MG", {}},
    {"MW", {"Zambia", "Tanzania", "Mozambique"}},
    {"MY", {"Thailand", "Brunei", "Indonesia"}},
    {"MV", {}},
    {"ML", {"Mauritania", "Algeria", "Niger", "Burkina Faso", "Ivory Coast", "Guinea", "Senegal"}},
    {"MT", {}},
    {"MH", {}},
    {"MR", {"Western Sahara", "Algeria", "Mali", "Senegal"}},
    {"MU", {}},
    {"MX", {"United States", "Guatemala", "Belize"}},
    {"FM", {}},
    {"MD", {"Ukraine", "Romania"}},
    {"MC", {"France"}},
    {"MN", {"Russia", "China"}},
    {"ME", {"Croatia", "Bosnia and Herzegovina", "Serbia", "Kosovo", "Albania"}},
    {"MA", {"Algeria", "Western Sahara"}},
    {"MZ", {"Tanzania", "Malawi", "Zambia", "Zimbabwe", "South Africa", "Eswatini"}},
    {"MM", {"India", "China", "Bangladesh", "Laos", "Thailand"}},
    {"NA", {"Angola", "Zambia", "Botswana", "South Africa"}},
    {"NR", {}},
    {"NP", {"India", "China"}},
    {"NL", {"Belgium", "Germany"}},
    {"NZ", {}},
    {"NI", {"Honduras", "Costa Rica"}},
    {"NE", {"Libya", "Chad", "Nigeria", "Benin", "Burkina Faso", "Mali", "Algeria"}},
    {"NG", {"Benin", "Niger", "Chad", "Cameroon"}},
    {"NO", {"Sweden", "Finland", "Russia"}},
    {"OM", {"United Arab Emirates", "Saudi Arabia", "Yemen"}},
    {"PK", {"India", "Afghanistan", "Iran", "China"}},
    {"PW", {}},
    {"PS", {"Israel", "Egypt", "Jordan"}},
    {"PA", {"Costa Rica", "Colombia"}},
    {"PG", {"Indonesia"}},
    {"PY", {"Brazil", "Argentina", "Bolivia"}},
    {"PE", {"Ecuador", "Colombia", "Brazil", "Bolivia", "Chile"}},
    {"PH", {}},
    {"PL", {"Germany", "Czechia", "Slovakia", "Ukraine", "Belarus", "Lithuania"}},
    {"PT", {"Spain"}},
    {"QA", {"Saudi Arabia"}},
    {"RO", {"Ukraine", "Moldova", "Hungary", "Serbia", "Bulgaria"}},
    {"RU", {"Norway", "Finland", "Estonia", "Latvia", "Lithuania", "Poland", "Belarus", "Ukraine", "Georgia", "Azerbaijan", "Kazakhstan", "China", "Mongolia", "North Korea"}},
    {"RW", {"Uganda", "Tanzania", "Burundi", "Democratic Republic of the Congo"}},
    {"KN", {}},
    {"LC", {}},
    {"VC", {}},
    {"WS", {}},
    {"SM", {"Italy"}},
    {"ST", {}},
    {"SA", {"Jordan", "Iraq", "Kuwait", "Qatar", "United Arab Emirates", "Oman", "Yemen"}},
    {"SN", {"Mauritania", "Mali", "Guinea", "Guinea-Bissau", "Gambia"}},
    {"RS", {"Hungary", "Romania", "Bulgaria", "North Macedonia", "Albania", "Montenegro", "Bosnia and Herzegovina", "Croatia"}},
    {"SC", {}},
    {"SL", {"Guinea", "Liberia"}},
    {"SG", {"Malaysia"}},
    {"SK", {"Czechia", "Poland", "Ukraine", "Hungary", "Austria"}},
    {"SI", {"Italy", "Austria", "Hungary", "Croatia"}},
    {"SB", {}},
    {"SO", {"Ethiopia", "Kenya", "Djibouti"}},
    {"ZA", {"Namibia", "Botswana", "Zimbabwe", "Mozambique", "Eswatini", "Lesotho"}},
    {"ES", {"France", "Andorra", "Portugal", "Gibraltar (UK territory)"}},
    {"LK", {}},
    {"SD", {"Egypt", "Libya", "Chad", "Central African Republic", "South Sudan", "Eritrea"}},
    {"SR", {"Guyana", "Brazil", "French Guiana"}},
    {"SE", {"Norway", "Finland"}},
    {"CH", {"Germany", "France", "Italy", "Austria", "Liechtenstein"}},
    {"SY", {"Turkey", "Iraq", "Jordan", "Israel", "Lebanon"}},
    {"TW", {}},
    {"TJ", {"Uzbekistan", "Kyrgyzstan", "China", "Afghanistan"}},
    {"TZ", {"Kenya", "Uganda", "Rwanda", "Burundi", "Zambia", "Malawi", "Mozambique"}},
    {"TH", {"Myanmar", "Laos", "Cambodia", "Malaysia"}},
    {"TL", {"Indonesia"}},
    {"TG", {"Ghana", "Burkina Faso", "Benin"}},
    {"TO", {}},
    {"TT", {}},
    {"TN", {"Algeria", "Libya"}},
    {"TR", {"Greece", "Bulgaria", "Georgia", "Armenia", "Azerbaijan", "Iran", "Iraq", "Syria"}},
    {"TM", {"Iran", "Afghanistan", "Uzbekistan", "Kazakhstan"}},
    {"TV", {}},
    {"UG", {"South Sudan", "Kenya", "Tanzania", "Rwanda", "Democratic Republic of the Congo"}},
    {"UA", {"Poland", "Slovakia", "Hungary", "Romania", "Moldova", "Belarus", "Russia"}},
    {"AE", {"Saudi Arabia", "Oman"}},
    {"GB", {"Ireland"}},
    {"US", {"Canada", "Mexico"}},
    {"UY", {"Brazil", "Argentina"}},
    {"UZ", {"Kazakhstan", "Kyrgyzstan", "Tajikistan", "Afghanistan", "Turkmenistan"}},
    {"VU", {}},
    {"VE", {"Colombia", "Brazil", "Guyana"}},
    {"VN", {"China", "Laos", "Cambodia"}},
    {"YE", {"Saudi Arabia", "Oman"}},
    {"ZM", {"Tanzania", "Malawi", "Mozambique", "Zimbabwe", "Botswana", "Namibia", "Angola", "Democratic Republic of the Congo"}},
    {"ZW", {"Zambia", "Mozambique", "South Africa", "Botswana"}}};

#endif 
